//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUN_FUNCIONARIO
    {
        public int ID_FUNCIONARIO { get; set; }
        public int ID_FUNCIONES { get; set; }
    
        public virtual FUNCIONES FUNCIONES { get; set; }
    }
}
