//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rh.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_RHumanosEntities : DbContext
    {
        public DB_RHumanosEntities()
            : base("name=DB_RHumanosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BENEFICIOS> BENEFICIOS { get; set; }
        public virtual DbSet<CATEGORIAS> CATEGORIAS { get; set; }
        public virtual DbSet<DEDUCCIONES> DEDUCCIONES { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DETALLEPLANILLABEN> DETALLEPLANILLABEN { get; set; }
        public virtual DbSet<DETALLEPLATILLADED> DETALLEPLATILLADED { get; set; }
        public virtual DbSet<FUN_FUNCIONARIO> FUN_FUNCIONARIO { get; set; }
        public virtual DbSet<FUNCIONES> FUNCIONES { get; set; }
        public virtual DbSet<PLANILLA> PLANILLA { get; set; }
        public virtual DbSet<TBFUNCIONARIO> TBFUNCIONARIO { get; set; }
    }
}
