//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANILLA
    {
        public int ID_PLANILLA { get; set; }
        public System.DateTime PLAFECHA { get; set; }
        public string SEDE { get; set; }
        public float PLATOTAL { get; set; }
    }
}
