//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rh.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBFUNCIONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBFUNCIONARIO()
        {
            this.CATEGORIAS = new HashSet<CATEGORIAS>();
        }
    
        public int ID_FUNCIONARIO { get; set; }
        public string FUNNOMBRE { get; set; }
        public string FUNAPELLIDO1 { get; set; }
        public string FUNAPELLIDO2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORIAS> CATEGORIAS { get; set; }
    }
}
